### ISSUE TITLE
verify_*(assert_nothing=True) raises always

### ISSUE THREAD

**Issue by GsakuL** [CraftSpider/dpytest#12]
the assert_nothing itself is working, but it won't return.
It then tries to deque a message, fails, gets QueueEmpty and raises AssertionError.

https://github.com/CraftSpider/dpytest/blob/56e2a4834dc6e005ef4d68c76ab6f9216e69a372/discord/ext/test/runner.py#L47-L57

**Comment by Sergeileduc** [comment]
I think it has been fixed here :

https://github.com/CraftSpider/dpytest/blob/7e19bcd8f977a3fb51d48c73a8b927048388c59b/discord/ext/test/runner.py#L45-L51
