### ISSUE TITLE
backend (0.0.21) fails to send embeds

### ISSUE THREAD

**Issue by Sergeileduc** [CraftSpider/dpytest#26]
Hi !

I recently upgraded to 0.0.21, and I just found it breaks my "embeds" tests.

I have a cog with a simple command :

```python
    @commands.command()
    async def pypiembed(self, ctx):
        """Send test embed."""
        embed = discord.Embed(title="This is a test",
                            description="dummy test",  # noqa: E501
                            color=0x0000FF,
                            url="https://pypi.org/")

        await ctx.send(embed=embed)
```

and my unit test :
```python
@pytest.mark.asyncio
async def test_pypiembed():
    await dpytest.message('!pypiembed')

    expected_embed = discord.Embed(title="This is a test",
                                   description="dummy test",
                                   color=0x0000FF,
                                   url="https://pypi.org/")

    dpytest.verify_embed(embed=expected_embed)
```

(I create the bot, configure it and add the cog in conftest and in autouse fixture)

STDERR :
```shell
Ignoring exception in command pypiembed:
Traceback (most recent call last):
  File "/home/serge/Dev/DCTbot/.venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/serge/Dev/DCTbot/cogs/misc.py", line 41, in pypiembed
    await ctx.send(embed=embed)
  File "/home/serge/Dev/DCTbot/.venv/lib/python3.7/site-packages/discord/abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/serge/Dev/DCTbot/.venv/lib/python3.7/site-packages/discord/ext/test/backend.py", line 84, in send_message
    channel=channel, author=self.state.user, content=content, tts=tts, embeds=embeds, nonce=nonce
  File "/home/serge/Dev/DCTbot/.venv/lib/python3.7/site-packages/discord/ext/test/backend.py", line 562, in make_message
    mentions = find_user_mentions(content, guild)
  File "/home/serge/Dev/DCTbot/.venv/lib/python3.7/site-packages/discord/ext/test/backend.py", line 593, in find_user_mentions
    matches = re.findall(MEMBER_MENTION, content)
  File "/home/serge/Dev/DCTbot/.venv/lib/python3.7/re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```

I think `make_message` fails because there is no "content" in a message containing only embeds, and `find_user_mentions` regex fails on that.

Anybody can reproduce ? Test on simple embed ?

**Comment by bravosierra99** [comment]
I'm running into the same issue, but it seems to be much deeper (though my understanding of what is going on is tenuous) I've changed the code to handle when there content is empty, however it seems to run into a problem within message.py of discord having to do with channel mentions.  The init function for Message does not ever seem to fill out channel_mentions, which I don't understand.  so it just has an empty slot, maybe it needs to be filled out in a different way (they have handlers for most everything else).  I'm going to keep looking at it.

**Comment by bravosierra99** [comment]
so I may have fixed it, but my tests are running into other issues so I don't want to push any commits atm.  For some reason I can watch my code raise  CommandError, but the error_queue.empty() == True which means pytest  fails.
