### ISSUE TITLE
message.mentions is always empty

### ISSUE THREAD

**Issue by yobuntu** [CraftSpider/dpytest#4]
backend.make_message does not parse the message content to extract mentioned user.

I don't know much about discord, but it seems we should ideally extract all the  matches of '^<@[0-9]{18}>$' and compare them with members of the channel the message is posted in to extract the mentioned users.

But maybe only extract the matching strings would be good enough.

**Comment by Sergeileduc** [comment]
PR #6 should fix this.

**Comment by CraftSpider** [comment]
Yes. Looking at it, I can't remember if d.py mentions includes role/channel mentions, but the merged fix implements the most common use anyways
