### ISSUE TITLE
Ongoing Maintenance

### ISSUE THREAD

**Issue by CraftSpider** [CraftSpider/dpytest#40]
I do not currently have the time or motivation to properly maintain this library. @bravosierra99 I've heard you have been maintaining an up-to-date fork, would you be interested in being given access to upstream your changes into this repo and ability to push updates to the `dpytest` package on pip?
Alternatively, I could just update the README to point to a maintained downstream. I don't mind either way, but would like to make sure there remains one place to find info about this package.

**Comment by CraftSpider** [comment]
CC @Sergeileduc

**Comment by bravosierra99** [comment]
I would just do the second. That being said, your name would be enshrined forever for making this super useful library. I would have to learn about the pypi part. If you truly don't mind then that's what I would do. If you think you might come back, then we could look at the first option.

**Comment by Sergeileduc** [comment]
Wow @CraftSpider , that would be my great honor, dude.

I made a very small project on PyPI, that you can find here : https://pypi.org/project/py-casim/

I'm not a master of the PyPI-fu, but you know... I try !

Seriously, that would be an honor, to maintain this great lib' that you created (and merge the code from @bravosierra99 of course, who also did a great work, and why not, teach him the secrets of PyPi-FU ?)

Again, thank you for your offer, that would be an honor.
See yah !

**Comment by JayDwee** [comment]
@bravosierra99 @Sergeileduc @CraftSpider Has there been an update on this, our development team over at https://koalabot.uk really appreciate this repo and we'd love to see it (or a downstream) continue to be supported.

**Comment by bravosierra99** [comment]
I got the impression @Sergeileduc was taking over. I agree. Great repo. Haven't had much time for my bot so I haven't been running any tests. 

@Sergeileduc you still here?  You taking over?

**Comment by CraftSpider** [comment]
I just invited Sergeileduc on as a collaborator, sorry I didn't do it earlier! Assuming they accept, I'll make sure they have the power to make changes, and work on setting up the PyPi part. I will at least try to be around to help with that part if necessary.

**Comment by Sergeileduc** [comment]
Hi guys !

Just saw that. Thanks !

I will look into it this weekend (probably).

See yah !

**Comment by Sergeileduc** [comment]
@CraftSpider for the PyPi part, I think you just need to add me as a `Maintainer` (Your projects -> dpytest -> Manage -> Collaborators`

Same name (`Sergeileduc`).

I think I will be able to generate my own token, for pushing new versions, etc...

**Comment by JayDwee** [comment]
can we get a dpytest support discord 🥺

**Comment by Sergeileduc** [comment]
> can we get a dpytest support discord 🥺

Sure ! Great Idea !

Just created a Discord (not fancy, I'll look into it more this week end)

7-days (after expiration) invitation link :

https://discord.gg/BZPCWmYT

**Comment by Sergeileduc** [comment]
Hello @CraftSpider !
Can I bother you (for 2 minutes ?)

We created a discord (invitation link in the README).

That would be really really cool, if you can set up the "webhook" thing between Github and Discord (I need to create a webhook url, but I can't share it in public, because evryone with this url could spam the discord...)

The tuto to link Github and discord is here : https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22
(except for Step 1 : I'll do it, and I will give you the URL)

We just need to find a place where I can send you the webhook URL.

I don't know how you want to do this ? Mail ? Discord MP ?

**Comment by CraftSpider** [comment]
Hey, you can send it to me over discord. I just joined the server, feel free to DM that account. I've used discord/github webhooks before, so feel free to just send me the link and I'll get it set up.

**Comment by Sergeileduc** [comment]
We all are on Discord, now, if we want to talk, etc...

Closing the issue.
