### ISSUE TITLE
Tests in classes don't work

### ISSUE THREAD

**Issue by Bwallker** [CraftSpider/dpytest#65]
### Is your feature request related to a problem? Please describe.
I would like to put my tests into classes, but if I do they don't work

![image](https://user-images.githubusercontent.com/58291118/126476136-6b780029-d068-45a4-9a5a-4073080bdee6.png)
![image](https://user-images.githubusercontent.com/58291118/126476451-13ce6368-1cf5-4433-a9fb-45cc80ed3fa1.png)

with this setup my test runs as you would expect and fails because of an exception I throw. this is supposed to happen.

![image](https://user-images.githubusercontent.com/58291118/126476378-cee71f45-59eb-4896-92a8-0273e7480c56.png)
![image](https://user-images.githubusercontent.com/58291118/126476547-21865739-b81a-4afb-9982-a5dac10601bd.png)

However when I put my test and fixture into a class it no longer works
Having the fixture outside the class and the test inside the class doesn't work either
### Describe the solution you'd like
If this is a limitation or a bug in dpytest, I would like it fixed. If it is something I am doing wrong, I would like to know how I can get it to work

### Describe alternatives you've considered
Not putting my tests into classes. But I think this is messy and I prefer having them in classes :/

**Comment by Bwallker** [comment]
The class I am using inherits from unittest.TestCase

**Comment by Sillocan** [comment]
unittest.TestCase does not support pytest fixtures out of the box. You have to do a bit of work to get them to work. This isn't a dpytest issue. https://docs.pytest.org/en/6.2.x/unittest.html

**Comment by Sergeileduc** [comment]
thanks for the answer @Sillocan !

I'll close the issue, I think.
