### ISSUE TITLE
Problems with send_message()

### ISSUE THREAD

**Issue by Excalibur8201** [CraftSpider/dpytest#77]
From versions on py-cord 2.0.0 and discord.py 2.0.0. This error happens:

**discord TypeError: send_message() got an unexpected keyword argument 'embeds'**

For what I´ve seen, The discord.ext.test.backend.FakeHttp.send_message has only embed argument, not also "embeds" as the new libraries versions.

**Comment by Sergeileduc** [comment]
we updated the lib, so it's okay with discord.py 2

Is your problem still there ?
