### ISSUE TITLE
channel.set_permissions not implemented

### ISSUE THREAD

**Issue by GsakuL** [CraftSpider/dpytest#8]
My bot has some administration commands, which are tied to channel permissions. The Bot will respond in different ways, if it either has permissions (execute command) or not (send error message) to inform the user/admin.
```py
import discord.ext.test as dpytest
import pytest
from discord import Guild, TextChannel
from discord.ext.commands import Bot

@pytest.mark.asyncio
async def test_permission():
    bot = Bot("!", formatter=None)
    dpytest.configure(bot, num_members=3, num_channels=2)
    guild: Guild = bot.guilds[0]
    channel: TextChannel = guild.text_channels[1]
    await channel.set_permissions(guild.default_role, send_messages=False, read_messages=False)
    # ...
```

**Comment by GsakuL** [comment]
... also there is no good way of updating / creating a text channel with overrides.
(But if there is, it's not documented)

**Comment by CraftSpider** [comment]
I don't think there currently is a good way to do that, I'll look into setting up permissions and channel overrides when I have the time

**Comment by GsakuL** [comment]
So I took a quick look.
Maybe I can help and do it.
I'm not sure if someone wants to mock some complex permissions with lots of roles and personal overrides, but for now some simple ones should be possible (we have to start somewhere anyway).
I also think we can use some calculation/translation (names<->numbers) of permissions directly from dpy

If you decided how to lay out tests, I could also add some appropriate ones.

- [ ] implement perm setting
- [ ] Implement perm reading / checking
- [ ] raise perm errors for bots
- [ ] Test(s)
